version: '1.0'

services:
  api-type:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-type
    ports:
      - "3000:3000"
    networks:
      - api-type

  db:
    image: mysql:8.0
    container_name: ${DATABASE_HOST}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - api-type

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8989:80"
    environment:
      PMA_HOST: ${DATABASE_HOST}
      PMA_PORT: ${DATABASE_PORT}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - api-type

volumes:
  db_data: